package codegen

const goTemplate = `
// Generated by Meduza. Do not rewrite unless you know what you're doing...

package model

import "github.com/EverythingMe/meduza/schema"

{{ define "Column" }}\
{{ .GoName }} schema.{{.Type}} ~db:"{{.Name}}\
{{ if .Options.required }},required{{end}}"\
{{ if .Options.max_len }} maxlen:"{{ .Options.max_len }}"{{end}}\
{{ if .Options.subtype }} type:"{{ .Options.subtype }}"{{end}}\
{{ if .HasDefault }} default:"{{ getDefault .Default "go" }}"{{end}}\
~
{{end}}
{{ $sc := .Name }}\
const Schema_{{.Name}} = "{{.Name}}"

{{ range .Tables }}

const Table_{{ .BaseName}} = "{{.BaseName}}"

{{ if .Comment }}// {{ .Class }} {{ .Comment }} {{ end }}
type {{ .Class }} struct {

    _ struct{} ~table:"{{.BaseName}}" schema:"{{ $sc }}"~
	Id schema.Key ~db:",primary"~
{{ range .Columns }}\
{{ if ne .Comment ""}}
    // {{ .Comment }}
{{end}}\
    {{ template "Column" . }}\
{{ end }}\
}
{{ end }}`
