package codegen

const pythonTemplate = `
"""
Generated by Meduza. Do not rewrite unless you know what you're doing...
"""

{{ define "Column" }}\
{{ .ClientName }} = {{.Type}}('{{.Name}}'\
{{ if .Options.required }}, required=True{{end}}\
{{ if .Options.max_len }}, maxLen={{ .Options.max_len }}{{end}}\
{{ if .Options.subtype }}, type={{ .Options.subtype }}(){{end}}\
{{ if .HasDefault }}, default={{ getDefault .Default "py" }}{{end}}\
)
{{end}}

from meduza.model import Model
from meduza.columns import *

## Start schema {{ .Name }}
{{ $sc := .Name }}\
{{ range .Tables }}

class {{ .Class }}(Model):

    _table = '{{.BaseName}}'
    _schema = '{{$sc}}'

{{ range .Columns }}\
{{ if ne .Comment ""}}    # {{ .Comment }}
{{end}}\
    {{ template "Column" . }}
{{ end }}\

{{ end }}
## End schema {{ .Name }}
`
